# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import chat_pb2 as protos_dot_chat__pb2


class ChatStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateRoom = channel.unary_unary(
                '/Chat/CreateRoom',
                request_serializer=protos_dot_chat__pb2.CreateRequest.SerializeToString,
                response_deserializer=protos_dot_chat__pb2.CreateResponse.FromString,
                )
        self.ListRooms = channel.unary_unary(
                '/Chat/ListRooms',
                request_serializer=protos_dot_chat__pb2.ListRequest.SerializeToString,
                response_deserializer=protos_dot_chat__pb2.ListResponse.FromString,
                )
        self.GetRoomInfo = channel.unary_unary(
                '/Chat/GetRoomInfo',
                request_serializer=protos_dot_chat__pb2.InfoRequest.SerializeToString,
                response_deserializer=protos_dot_chat__pb2.InfoResponse.FromString,
                )
        self.JoinRoom = channel.unary_unary(
                '/Chat/JoinRoom',
                request_serializer=protos_dot_chat__pb2.JoinRequest.SerializeToString,
                response_deserializer=protos_dot_chat__pb2.JoinResponse.FromString,
                )
        self.LeaveRoom = channel.unary_unary(
                '/Chat/LeaveRoom',
                request_serializer=protos_dot_chat__pb2.LeaveRequest.SerializeToString,
                response_deserializer=protos_dot_chat__pb2.LeaveResponse.FromString,
                )
        self.GetMessages = channel.unary_stream(
                '/Chat/GetMessages',
                request_serializer=protos_dot_chat__pb2.GetMessagesRequest.SerializeToString,
                response_deserializer=protos_dot_chat__pb2.ChatMessage.FromString,
                )
        self.SendMessage = channel.unary_unary(
                '/Chat/SendMessage',
                request_serializer=protos_dot_chat__pb2.SendRequest.SerializeToString,
                response_deserializer=protos_dot_chat__pb2.SendResponse.FromString,
                )


class ChatServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateRoom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRooms(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRoomInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JoinRoom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LeaveRoom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRoom,
                    request_deserializer=protos_dot_chat__pb2.CreateRequest.FromString,
                    response_serializer=protos_dot_chat__pb2.CreateResponse.SerializeToString,
            ),
            'ListRooms': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRooms,
                    request_deserializer=protos_dot_chat__pb2.ListRequest.FromString,
                    response_serializer=protos_dot_chat__pb2.ListResponse.SerializeToString,
            ),
            'GetRoomInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRoomInfo,
                    request_deserializer=protos_dot_chat__pb2.InfoRequest.FromString,
                    response_serializer=protos_dot_chat__pb2.InfoResponse.SerializeToString,
            ),
            'JoinRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.JoinRoom,
                    request_deserializer=protos_dot_chat__pb2.JoinRequest.FromString,
                    response_serializer=protos_dot_chat__pb2.JoinResponse.SerializeToString,
            ),
            'LeaveRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.LeaveRoom,
                    request_deserializer=protos_dot_chat__pb2.LeaveRequest.FromString,
                    response_serializer=protos_dot_chat__pb2.LeaveResponse.SerializeToString,
            ),
            'GetMessages': grpc.unary_stream_rpc_method_handler(
                    servicer.GetMessages,
                    request_deserializer=protos_dot_chat__pb2.GetMessagesRequest.FromString,
                    response_serializer=protos_dot_chat__pb2.ChatMessage.SerializeToString,
            ),
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=protos_dot_chat__pb2.SendRequest.FromString,
                    response_serializer=protos_dot_chat__pb2.SendResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Chat', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Chat(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Chat/CreateRoom',
            protos_dot_chat__pb2.CreateRequest.SerializeToString,
            protos_dot_chat__pb2.CreateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListRooms(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Chat/ListRooms',
            protos_dot_chat__pb2.ListRequest.SerializeToString,
            protos_dot_chat__pb2.ListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRoomInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Chat/GetRoomInfo',
            protos_dot_chat__pb2.InfoRequest.SerializeToString,
            protos_dot_chat__pb2.InfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def JoinRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Chat/JoinRoom',
            protos_dot_chat__pb2.JoinRequest.SerializeToString,
            protos_dot_chat__pb2.JoinResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LeaveRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Chat/LeaveRoom',
            protos_dot_chat__pb2.LeaveRequest.SerializeToString,
            protos_dot_chat__pb2.LeaveResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Chat/GetMessages',
            protos_dot_chat__pb2.GetMessagesRequest.SerializeToString,
            protos_dot_chat__pb2.ChatMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Chat/SendMessage',
            protos_dot_chat__pb2.SendRequest.SerializeToString,
            protos_dot_chat__pb2.SendResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
